name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetches the entire history to ensure we can use it

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Build the site
        run: |
          # Add any build commands here if needed
          # Example: npm install && npm run build
          echo "No build step required."

      - name: Deploy to GitHub Pages
        run: |
          git add --all
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
